// Shared information architecture. No React or platform dependencies.
export type Language = "ru" | "en" | "pl" | "es" | "fr" | "de" | "it";
export type Label = Record<Language, string>;
export const words = (ru: string, en: string, pl: string, es: string, fr: string, de: string, it: string): Label => ({ ru, en, pl, es, fr, de, it });
export type Section = "home" | "learn" | "practice" | "race" | "library";
export const sections: { id: Section; web: string; native: string; title: Label; description: Label; icon: string }[] = [
  { id: "home", web: "/", native: "/", icon: "sail", title: words("Главная", "Home", "Start", "Inicio", "Accueil", "Start", "Home"), description: words("Твой следующий шаг", "Your next step", "Twój kolejny krok", "Tu siguiente paso", "Ta prochaine étape", "Dein nächster Schritt", "Il tuo prossimo passo") },
  { id: "learn", web: "/learn", native: "/learn", icon: "book", title: words("Обучение", "Learn", "Nauka", "Aprender", "Apprendre", "Lernen", "Impara"), description: words("От первых шагов до подготовки к экзамену.", "From your first steps to exam preparation.", "Od pierwszych kroków do egzaminu.", "Desde los primeros pasos hasta el examen.", "Des premiers pas à la préparation aux examens.", "Von den ersten Schritten bis zur Prüfung.", "Dai primi passi alla preparazione agli esami.") },
  { id: "practice", web: "/practice", native: "/simulators", icon: "simulator", title: words("Практика", "Practice", "Trening", "Practicar", "Pratiquer", "Üben", "Pratica"), description: words("Сначала ветер и повороты. Затем трим и паруса в 3D.", "Start with wind and turns. Then explore trim and 3D sails.", "Zacznij od wiatru i zwrotów. Potem trym i żagle 3D.", "Empieza con viento y giros. Después, trimado y velas 3D.", "D'abord le vent et les virements. Puis le réglage et les voiles 3D.", "Erst Wind und Wenden. Dann Trimm und 3D-Segel.", "Prima vento e virate. Poi regolazione e vele 3D.") },
  { id: "race", web: "/race", native: "/race", icon: "flag", title: words("Гонка", "Race", "Regaty", "Regata", "Course", "Rennen", "Regata"), description: words("Потренируйся один или пригласи друзей на дистанцию.", "Practise solo or invite friends onto the course.", "Trenuj sam lub zaproś znajomych na trasę.", "Practica solo o invita a tus amigos.", "Entraîne-toi seul ou invite tes amis.", "Übe allein oder lade Freunde auf den Kurs ein.", "Allenati da solo o invita gli amici sul percorso.") },
  { id: "library", web: "/library", native: "/library", icon: "glossary", title: words("Справочник", "Library", "Biblioteka", "Biblioteca", "Bibliothèque", "Wissen", "Biblioteca"), description: words("Найди нужную тему, инструмент или раздел.", "Find a topic, tool or section.", "Znajdź temat, narzędzie lub dział.", "Busca un tema, herramienta o sección.", "Trouve un sujet, un outil ou une rubrique.", "Finde Themen, Werkzeuge und Bereiche.", "Trova un argomento, strumento o sezione.") },
];
export interface Destination { id: string; section: Exclude<Section, "home">; web: string | null; native: string | null; title: Label; detail?: Label; online?: boolean; certificate?: boolean }
export const destinations: Destination[] = [
  { id: "course", section: "learn", web: "/start", native: "/bootcamp", title: words("Парусный спорт с нуля", "Sailing from the start", "Żeglarstwo od podstaw", "Vela desde cero", "Débuter la voile", "Segeln von Anfang an", "Vela da zero"), detail: words("8 коротких уроков: ветер, паруса, повороты и первая гонка.", "8 short lessons: wind, sails, turns and your first race.", "8 krótkich lekcji: wiatr, żagle, zwroty i pierwsze regaty.", "8 lecciones: viento, velas, giros y tu primera regata.", "8 leçons : vent, voiles, virements et première course.", "8 kurze Lektionen: Wind, Segel, Wenden und dein erstes Rennen.", "8 brevi lezioni: vento, vele, virate e la prima regata.") },
  { id: "quick", section: "learn", web: "/quick", native: "/quick", title: words("Повторить за 15 минут", "15-minute refresher", "Powtórka w 15 minut", "Repaso en 15 minutos", "Réviser en 15 minutes", "15 Minuten Auffrischung", "Ripasso in 15 minuti") },
  { id: "rules", section: "learn", web: "/rules", native: "/rules", title: words("Правила гонок", "Racing rules", "Przepisy regatowe", "Reglas de regata", "Règles de course", "Wettfahrtregeln", "Regole di regata") },
  { id: "tactics", section: "learn", web: "/racing", native: "/racing", title: words("Тактика", "Tactics", "Taktyka", "Táctica", "Tactique", "Taktik", "Tattica") },
  { id: "points", section: "learn", web: "/courses", native: "/courses", title: words("Курсы относительно ветра", "Points of sail", "Kursy względem wiatru", "Rumbos respecto al viento", "Allures", "Kurse zum Wind", "Andature") },
  { id: "radio", section: "learn", certificate: true, web: "/radio", native: "/kursy/radio", title: words("Радиосвязь SRC", "SRC radio", "Radio SRC", "Radio SRC", "Radio SRC", "SRC-Funk", "Radio SRC"), detail: words("Курс и подготовка к экзамену UKE в Польше.", "Course and preparation for the Polish UKE exam.", "Kurs i przygotowanie do egzaminu UKE.", "Curso y preparación para el examen UKE de Polonia.", "Cours et préparation à l'examen UKE en Pologne.", "Kurs und Vorbereitung auf die polnische UKE-Prüfung.", "Corso e preparazione all'esame UKE in Polonia.") },
  { id: "motor", section: "learn", certificate: true, web: "/sternik", native: "/kursy/motorowodny", title: words("Моторный рулевой", "Motorboat skipper", "Sternik motorowodny", "Patrón de motor", "Permis moteur", "Motorbootführer", "Patente a motore"), detail: words("Курс sternik motorowodny и экзаменационная практика в Польше.", "Polish sternik motorowodny course and exam practice.", "Kurs sternika motorowodnego i ćwiczenia egzaminacyjne.", "Curso polaco sternik motorowodny y práctica de examen.", "Cours polonais sternik motorowodny et exercices d'examen.", "Polnischer Kurs sternik motorowodny und Prüfungsübungen.", "Corso polacco sternik motorowodny ed esercizi d'esame.") },
  { id: "basics", section: "practice", online: true, web: "/simulator", native: "/simulator-v1", title: words("Основы", "Basics", "Podstawy", "Fundamentos", "Bases", "Grundlagen", "Basi"), detail: words("Начни здесь: меняй ветер и учись поворачивать.", "Start here: change the wind and learn to turn.", "Zacznij tutaj: zmieniaj wiatr i ucz się zwrotów.", "Empieza aquí: cambia el viento y aprende a girar.", "Commence ici : change le vent et apprends les virements.", "Hier starten: Wind ändern und Wenden lernen.", "Inizia qui: cambia il vento e impara le virate.") },
  { id: "trainer", section: "practice", online: true, web: "/simulator-v3", native: "/simulator-v3", title: words("Тренажёр трима", "Sail trim trainer", "Trener trymu", "Entrenador de trimado", "Réglage des voiles", "Segeltrimm-Trainer", "Trainer di regolazione"), detail: words("Настраивай паруса и проходи упражнения со скоростью и креном.", "Trim the sails and practise with speed and heel feedback.", "Trymuj żagle i ćwicz z informacją o prędkości i przechyle.", "Ajusta las velas y practica con velocidad y escora.", "Règle les voiles et observe la vitesse et la gîte.", "Trimme die Segel mit Rückmeldung zu Fahrt und Krängung.", "Regola le vele e osserva velocità e sbandamento.") },
  { id: "boat", section: "practice", web: "/simulator2", native: "/simulator2", online: true, title: words("Лодка 3D", "3D Boat", "Łódka 3D", "Barco 3D", "Bateau 3D", "3D-Boot", "Barca 3D"), detail: words("Рассмотри форму парусов и их реакцию на ветер с любого ракурса.", "Inspect sail shape and wind response from every angle.", "Obejrzyj kształt żagli i ich reakcję na wiatr z każdej strony.", "Observa las velas y su respuesta al viento desde cualquier ángulo.", "Observe la forme des voiles et leur réaction au vent sous tous les angles.", "Betrachte Segelform und Windreaktion aus jedem Winkel.", "Osserva forma delle vele e risposta al vento da ogni angolo.") },
  { id: "solo", section: "race", web: "/game", native: "/game", title: words("Одиночная гонка", "Solo race", "Wyścig solo", "Regata individual", "Course solo", "Einzelrennen", "Regata singola"), detail: words("Выбери дистанцию и отработай старт, знаки и финиш.", "Choose a course and practise starts, marks and finishes.", "Wybierz trasę i przećwicz start, znaki oraz finisz.", "Elige un recorrido y practica salida, boyas y llegada.", "Choisis un parcours et travaille départ, marques et arrivée.", "Wähle einen Kurs und übe Start, Marken und Ziel.", "Scegli un percorso e prova partenza, boe e arrivo.") },
  { id: "multiplayer", section: "race", web: "/multiplayer", native: "/multiplayer", online: true, title: words("Гонка с друзьями", "Race with friends", "Regaty ze znajomymi", "Regata con amigos", "Course entre amis", "Rennen mit Freunden", "Regata con amici"), detail: words("Создай комнату или войди по коду приглашения.", "Create a room or join with an invitation code.", "Utwórz pokój lub dołącz kodem zaproszenia.", "Crea una sala o entra con un código.", "Crée un salon ou rejoins-le avec un code.", "Erstelle einen Raum oder tritt per Code bei.", "Crea una stanza o entra con un codice.") },
  { id: "leaderboard", section: "race", web: "/leaderboard", native: "/leaderboard", title: words("Результаты гонок", "Leaderboard", "Ranking", "Clasificación", "Classement", "Rangliste", "Classifica") },
  { id: "history", section: "race", web: null, native: "/history", title: words("Мои гонки", "My races", "Moje regaty", "Mis regatas", "Mes courses", "Meine Rennen", "Le mie regate") },
  { id: "anatomy", section: "library", web: "/anatomy", native: "/anatomy", title: words("Устройство яхты", "Yacht anatomy", "Budowa jachtu", "Anatomía del velero", "Anatomie du voilier", "Aufbau der Yacht", "Anatomia della barca") },
  { id: "onboard", section: "library", web: "/onboard", native: "/onboard", title: words("Первая неделя на борту", "First week on board", "Pierwszy tydzień na pokładzie", "Primera semana a bordo", "Première semaine à bord", "Erste Woche an Bord", "Prima settimana a bordo") },
  { id: "checklist", section: "library", web: "/checklist", native: "/checklist", title: words("Чек-лист перед выходом", "Before you sail", "Przed wypłynięciem", "Antes de zarpar", "Avant de partir", "Vor dem Ablegen", "Prima di salpare") },
  { id: "glossary", section: "library", web: "/glossary", native: "/glossary", title: words("Морские термины", "Sailing glossary", "Słownik żeglarski", "Glosario náutico", "Glossaire nautique", "Segellexikon", "Glossario nautico") },
  { id: "spots", section: "library", web: "/spots", native: "/spots", online: true, title: words("Места и погода", "Places and weather", "Miejsca i pogoda", "Lugares y tiempo", "Lieux et météo", "Reviere und Wetter", "Luoghi e meteo") },
  { id: "gallery", section: "library", web: "/gallery", native: "/gallery", title: words("Галерея", "Gallery", "Galeria", "Galería", "Galerie", "Galerie", "Galleria") },
  { id: "ask", section: "library", web: null, native: "/ask", online: true, title: words("Спросить ассистента", "Ask the assistant", "Zapytaj asystenta", "Pregunta al asistente", "Demander à l'assistant", "Assistenten fragen", "Chiedi all'assistente") },
  { id: "settings", section: "library", web: null, native: "/settings", title: words("Настройки", "Settings", "Ustawienia", "Ajustes", "Réglages", "Einstellungen", "Impostazioni") },
];
export function sectionForPath(path: string, platform: "web" | "native"): Section {
  const clean = path.split(/[?#]/)[0].replace(/\/$/, "") || "/";
  const hub = sections.find(s => s[platform] === clean);
  if (hub) return hub.id;
  const match = destinations.filter(d => d[platform] && (clean === d[platform] || clean.startsWith(d[platform] + "/")))
    .sort((a, b) => (b[platform]?.length ?? 0) - (a[platform]?.length ?? 0))[0];
  if (match) return match.section;
  if (clean.startsWith("/simulator")) return "practice";
  if (clean.startsWith("/replay") || clean === "/coach") return "race";
  return "library";
}
export function searchDestinations(query: string, lang: Language, platform: "web" | "native") {
  const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase().replace(/ё/g, "е").replace(/ł/g, "l");
  const terms = normalize(query.trim()).split(/\s+/).filter(Boolean);
  return destinations.filter(d => d[platform] && terms.every(term => normalize(`${d.title[lang]} ${d.title.en} ${d.detail?.[lang] ?? ""} ${d.id}`).includes(term)));
}
