import { words } from "./catalog";
export const copy = {
  hello: words("Парусный спорт. Шаг за шагом.", "Sailing. One step at a time.", "Żeglarstwo. Krok po kroku.", "Vela. Paso a paso.", "La voile. Pas à pas.", "Segeln. Schritt für Schritt.", "Vela. Un passo alla volta."),
  intro: words("Разберись с ветром, попробуй управление и выйди на первую гонку.", "Understand the wind, try the controls and sail your first race.", "Poznaj wiatr, spróbuj sterowania i wystartuj w pierwszych regatach.", "Conoce el viento, prueba los mandos y navega tu primera regata.", "Comprends le vent, essaie les commandes et lance ta première course.", "Verstehe den Wind, probiere die Steuerung und segle dein erstes Rennen.", "Comprendi il vento, prova i comandi e naviga la tua prima regata."),
  start: words("Начать первый урок", "Start the first lesson", "Zacznij pierwszą lekcję", "Empezar la primera lección", "Commencer la première leçon", "Erste Lektion starten", "Inizia la prima lezione"),
  resume: words("Продолжить обучение", "Continue learning", "Kontynuuj naukę", "Seguir aprendiendo", "Reprendre l'apprentissage", "Weiterlernen", "Continua a imparare"),
  overview: words("Все уроки", "All lessons", "Wszystkie lekcje", "Todas las lecciones", "Toutes les leçons", "Alle Lektionen", "Tutte le lezioni"),
  learned: words("Уроки пройдены. Попробуй гонку.", "Lessons complete. Try a race.", "Lekcje ukończone. Spróbuj regat.", "Lecciones completadas. Prueba una regata.", "Leçons terminées. Essaie une course.", "Lektionen abgeschlossen. Versuche ein Rennen.", "Lezioni completate. Prova una regata."),
  viewed: words("Просмотрено уроков", "Lessons visited", "Odwiedzone lekcje", "Lecciones visitadas", "Leçons consultées", "Besuchte Lektionen", "Lezioni visitate"),
  next: words("Следующий шаг", "Next step", "Następny krok", "Siguiente paso", "Prochaine étape", "Nächster Schritt", "Prossimo passo"),
  choose: words("Что попробуем?", "What would you like to try?", "Czego spróbujesz?", "¿Qué quieres probar?", "Que veux-tu essayer ?", "Was möchtest du ausprobieren?", "Cosa vuoi provare?"),
  search: words("Поиск по разделам", "Search sections", "Szukaj działów", "Buscar secciones", "Rechercher une rubrique", "Bereiche suchen", "Cerca sezioni"),
  hint: words("Например: радио, паруса, погода", "Try: radio, sails, weather", "Np. radio, żagle, pogoda", "Ej.: radio, velas, tiempo", "Ex. : radio, voiles, météo", "Z. B. Funk, Segel, Wetter", "Es.: radio, vele, meteo"),
  empty: words("Не нашли такой раздел. Попробуй другое слово.", "No matching section. Try another word.", "Nie znaleziono działu. Spróbuj innego słowa.", "Sin resultados. Prueba otra palabra.", "Aucun résultat. Essaie un autre mot.", "Kein Bereich gefunden. Versuche ein anderes Wort.", "Nessun risultato. Prova un'altra parola."),
  clear: words("Очистить поиск", "Clear search", "Wyczyść wyszukiwanie", "Borrar búsqueda", "Effacer la recherche", "Suche löschen", "Cancella ricerca"),
  exam: words("Курсы для экзамена в Польше", "Polish exam preparation", "Przygotowanie do egzaminu", "Preparación para exámenes en Polonia", "Préparation aux examens en Pologne", "Prüfungsvorbereitung in Polen", "Preparazione agli esami in Polonia"),
  sailing: words("Учимся ходить под парусом", "Learn to sail", "Uczymy się żeglować", "Aprende a navegar", "Apprendre à naviguer", "Segeln lernen", "Imparare a navigare"),
  online: words("Нужен интернет", "Internet required", "Wymaga internetu", "Requiere internet", "Internet requis", "Internet erforderlich", "Serve internet"),
  fallback: words("Без интернета: упрощённый тренажёр", "Offline: simplified trainer", "Offline: uproszczony trener", "Sin conexión: entrenador simplificado", "Hors ligne : entraîneur simplifié", "Offline: vereinfachter Trainer", "Offline: trainer semplificato"),
  daily: words("Гонка дня", "Daily race", "Regaty dnia", "Regata del día", "Course du jour", "Tagesrennen", "Regata del giorno"),
  minutes: words("мин", "min", "min", "min", "min", "Min.", "min"),
  navigation: words("Основные разделы", "Main sections", "Główne działy", "Secciones principales", "Rubriques principales", "Hauptbereiche", "Sezioni principali"),
  app: words("Приложение для iPhone и iPad", "App for iPhone and iPad", "Aplikacja na iPhone i iPad", "App para iPhone y iPad", "App pour iPhone et iPad", "App für iPhone und iPad", "App per iPhone e iPad"),
};
