'use client';

import type { TpFn } from "../shared";
import type { useTrainerCheckpoint } from "../../hooks/use-trainer-checkpoint";

export function CheckpointPanel({ checkpoint, canSave, tp }: {
  checkpoint: ReturnType<typeof useTrainerCheckpoint>; canSave: boolean; tp: TpFn;
}) {
  const message = {
    idle: "",
    saved: tp("Снимок сохранен на этом устройстве. Дальнейшие изменения автоматически не сохраняются.", "Checkpoint saved on this device. Later changes are not saved automatically.", "Zapisano na tym urządzeniu. Dalsze zmiany nie zapisują się automatycznie.", { es: "Guardado en este dispositivo. Los cambios posteriores no se guardan automáticamente.", fr: "Enregistré sur cet appareil. Les changements suivants ne sont pas enregistrés automatiquement.", de: "Auf diesem Gerät gespeichert. Weitere Änderungen werden nicht automatisch gespeichert.", it: "Salvato su questo dispositivo. Le modifiche successive non vengono salvate automaticamente." }),
    restored: tp("Восстановлено на паузе. Проверь настройки и нажми «Продолжить».", "Restored and paused. Check the controls, then press Resume.", "Wczytano z pauzą. Sprawdź nastawy i wybierz Wznów.", { es: "Restaurado en pausa. Revisa los controles y pulsa Continuar.", fr: "Restauré en pause. Vérifie les réglages puis choisis Reprendre.", de: "Pausiert wiederhergestellt. Prüfe die Einstellungen und wähle Fortsetzen.", it: "Ripristinato in pausa. Controlla le impostazioni e premi Riprendi." }),
    empty: tp("Сохраненного снимка пока нет.", "No saved checkpoint yet.", "Nie ma jeszcze zapisu.", { es: "Aún no hay guardado.", fr: "Aucune sauvegarde.", de: "Noch kein Speicherstand.", it: "Nessun salvataggio." }),
    unavailable: tp("Не удалось прочитать или сохранить снимок. Текущая лодка не сброшена. Повтори попытку.", "Could not read or save the checkpoint. The current boat was not reset. Try again.", "Nie udało się odczytać lub zapisać. Aktualny jacht nie został zresetowany. Spróbuj ponownie.", { es: "No se pudo leer o guardar. No se reinició el barco. Reintenta.", fr: "Lecture ou sauvegarde impossible. Le bateau n'a pas été réinitialisé. Réessaie.", de: "Lesen oder Speichern fehlgeschlagen. Das Boot wurde nicht zurückgesetzt. Erneut versuchen.", it: "Lettura o salvataggio non riuscito. La barca non è stata azzerata. Riprova." }),
    corrupt: tp("Снимок поврежден. Он не загружен и не удален; текущая сессия сохранена.", "The checkpoint is damaged. It was not loaded or deleted; the current session is unchanged.", "Zapis jest uszkodzony. Nie wczytano go ani nie usunięto; obecna sesja bez zmian.", { es: "Guardado dañado. No se cargó ni eliminó; la sesión actual no cambia.", fr: "Sauvegarde endommagée. Ni chargée ni supprimée ; la session reste intacte.", de: "Speicherstand beschädigt. Nicht geladen oder gelöscht; aktuelle Sitzung unverändert.", it: "Salvataggio danneggiato. Non caricato né eliminato; sessione invariata." }),
    incompatible: tp("Снимок от другой версии модели. Автоматическое преобразование недоступно; текущая сессия не изменена.", "This checkpoint uses another model version. Automatic conversion is unavailable; the current session is unchanged.", "Zapis pochodzi z innej wersji modelu. Brak automatycznej konwersji; sesja bez zmian.", { es: "Guardado de otra versión. Sin conversión automática; sesión sin cambios.", fr: "Sauvegarde d'une autre version. Pas de conversion automatique ; session inchangée.", de: "Andere Modellversion. Keine automatische Umwandlung; Sitzung unverändert.", it: "Altra versione del modello. Nessuna conversione automatica; sessione invariata." }),
  }[checkpoint.status];
  const button = "min-h-11 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-sm disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-[var(--accent-cyan)]";
  return <details data-testid="trainer-checkpoint" className="scroll-mt-20 text-[var(--text-secondary)]">
    <summary className="cursor-pointer py-3 text-sm">{tp("Сохранение сессии", "Session checkpoint", "Zapis sesji", { es: "Guardar sesión", fr: "Sauvegarde de session", de: "Sitzung speichern", it: "Salvataggio sessione" })}{checkpoint.available ? " •" : ""}</summary>
    <div className="space-y-3 pb-2">
      <p className="text-xs leading-relaxed">{tp("Один ручной снимок лодки, настроек и наблюдений опыта. Сохранение заменяет предыдущий снимок, восстановление заменяет текущую сессию и ставит ее на паузу. Без синхронизации между устройствами.", "One manual checkpoint of the boat, settings and experiment observations. Saving replaces the previous checkpoint; restoring replaces the current session and pauses it. No sync between devices.", "Jeden ręczny zapis jachtu, nastaw i obserwacji. Zapis zastępuje poprzedni; wczytanie zastępuje bieżącą sesję i włącza pauzę. Bez synchronizacji urządzeń.", { es: "Un guardado manual del barco, ajustes y observaciones. Guardar sustituye el anterior; restaurar sustituye la sesión actual y la pausa. Sin sincronización entre dispositivos.", fr: "Une sauvegarde manuelle du bateau, réglages et observations. Enregistrer remplace la précédente ; restaurer remplace la session et la met en pause. Pas de synchronisation entre appareils.", de: "Ein manueller Speicherstand für Boot, Einstellungen und Beobachtungen. Speichern ersetzt den vorherigen; Laden ersetzt und pausiert die Sitzung. Keine Gerätesynchronisierung.", it: "Un salvataggio manuale di barca, comandi e osservazioni. Salvare sostituisce il precedente; ripristinare sostituisce e mette in pausa la sessione. Nessuna sincronizzazione tra dispositivi." })}</p>
      {!canSave && <p className="text-xs">{tp("Сохранение доступно в свободном режиме и опыте со снастями. Экзаменационные таймеры не сохраняются.", "Saving is available in Free Sail and the rig experiment. Timed drills are not saved.", "Zapis dostępny w swobodnym pływaniu i doświadczeniu. Ćwiczenia na czas nie są zapisywane.", { es: "Disponible en navegación libre y experimento. No guarda ejercicios cronometrados.", fr: "Disponible en navigation libre et expérience. Les exercices chronométrés ne sont pas sauvegardés.", de: "In Freier Fahrt und im Versuch verfügbar. Zeitübungen werden nicht gespeichert.", it: "Disponibile in navigazione libera ed esperimento. Esercizi a tempo non salvati." })}</p>}
      <div className="flex flex-wrap gap-2 text-[var(--text-primary)]" aria-busy={checkpoint.busy}>
        <button className={button} disabled={checkpoint.busy || !canSave} onClick={checkpoint.save}>{tp("Сохранить", "Save checkpoint", "Zapisz", { es: "Guardar", fr: "Enregistrer", de: "Speichern", it: "Salva" })}</button>
        <button className={button} disabled={checkpoint.busy} onClick={checkpoint.restore}>{tp("Восстановить", "Restore checkpoint", "Wczytaj", { es: "Restaurar", fr: "Restaurer", de: "Wiederherstellen", it: "Ripristina" })}</button>
      </div>
      {message && <p role="status" className="text-sm leading-relaxed">{message}</p>}
    </div>
  </details>;
}
