'use client';

import type { TrimStudy, TrimStudyIssue } from "../../../sailing-lab/lessons/trim-study";
import type { TpFn } from "../shared";

const button = "min-h-11 rounded-md border border-[var(--border-subtle)] px-3 py-2 text-sm text-[var(--text-primary)] focus-visible:outline-2 focus-visible:outline-[var(--accent-cyan)]";

export function TrimStudyPanel({ study, start, cancel, record, answer, tp }: {
  study: TrimStudy | null; start(): void; cancel(): void; record(): void;
  answer(value: "angle-only" | "shape"): void; tp: TpFn;
}) {
  const title = tp("Опыт: тот же угол, другая форма", "Experiment: same angle, different shape", "Doświadczenie: ten sam kąt, inny kształt", { es: "Experimento: mismo ángulo, otra forma", fr: "Expérience : même angle, autre forme", de: "Versuch: gleicher Winkel, andere Form", it: "Esperimento: stesso angolo, altra forma" });
  if (!study) return <section className="space-y-3 py-3">
    <h3 className="text-base font-semibold text-[var(--text-primary)]">{title}</h3>
    <p className="text-sm leading-relaxed text-[var(--text-secondary)]">{tp("Сравни три установившихся состояния грота. Запуск создаст новую сессию с постоянным ветром; курс и работу со снастью обеспечивает помощник.", "Compare three settled mainsail states. Starting creates a new session with steady wind; an assistant holds course and handles the line.", "Porównaj trzy ustalone stany grota. Start tworzy nową sesję ze stałym wiatrem; pomocnik utrzymuje kurs i obsługuje linę.", { es: "Compara tres estados estables. Se inicia una sesión nueva con viento constante; un ayudante mantiene rumbo y maneja el cabo.", fr: "Compare trois états stabilisés. Le départ crée une nouvelle session à vent constant ; un assistant tient le cap et manœuvre la ligne.", de: "Vergleiche drei stabile Zustände. Der Start beginnt eine neue Sitzung mit konstantem Wind; ein Helfer hält Kurs und bedient die Leine.", it: "Confronta tre stati stabili. Inizia una nuova sessione con vento costante; un assistente tiene la rotta e manovra la cima." })}</p>
    <button className={button} onClick={start}>{tp("Начать опыт в новой сессии", "Start experiment in a new session", "Rozpocznij w nowej sesji", { es: "Iniciar en una sesión nueva", fr: "Démarrer une nouvelle session", de: "Versuch in neuer Sitzung starten", it: "Inizia in una nuova sessione" })}</button>
  </section>;
  const issue: Record<TrimStudyIssue, string> = {
    wait: tp("Дай лодке установиться: нужны три секунды без заметного изменения угла, twist и скорости. На паузе время не идет.", "Let the boat settle: angle, twist and speed must remain stable for three simulation seconds. Pause does not count.", "Poczekaj na trzy sekundy stabilnego kąta, skrętu i prędkości. Pauza nie jest liczona.", { es: "Espera tres segundos simulados de ángulo, torsión y velocidad estables. La pausa no cuenta.", fr: "Attends trois secondes simulées d'angle, vrillage et vitesse stables. La pause ne compte pas.", de: "Warte drei Simulationssekunden mit stabilem Winkel, Twist und Tempo. Pause zählt nicht.", it: "Attendi tre secondi simulati con angolo, twist e velocità stabili. La pausa non conta." }),
    setup: tp("Для исходной записи верни длину 9,0 m и каретку в центр или начни опыт заново.", "For the baseline, return to 9.0 m and a centered car, or restart the experiment.", "Dla stanu początkowego ustaw 9,0 m i wózek pośrodku albo zacznij od nowa.", { es: "Para la referencia, vuelve a 9,0 m y carro centrado o reinicia.", fr: "Pour la référence, reviens à 9,0 m et au chariot centré, ou recommence.", de: "Für den Ausgangswert 9,0 m und mittigen Traveller einstellen oder neu starten.", it: "Per il riferimento torna a 9,0 m e carrello al centro, oppure ricomincia." }),
    environment: tp("Изменились ветер, курс или другой парус. Верни исходные настройки либо начни новый опыт: иначе сравнение нечестное.", "Wind, course or another sail changed. Restore the original settings or restart for a fair comparison.", "Zmieniono wiatr, kurs lub drugi żagiel. Przywróć ustawienia albo zacznij od nowa, aby porównanie było miarodajne.", { es: "Cambió viento, rumbo u otra vela. Restaura los ajustes o reinicia para comparar.", fr: "Vent, cap ou autre voile modifiés. Rétablis les réglages ou recommence pour comparer.", de: "Wind, Kurs oder anderes Segel geändert. Für einen fairen Vergleich zurückstellen oder neu starten.", it: "Sono cambiati vento, rotta o altra vela. Ripristina o ricomincia per un confronto valido." }),
    ease: tp("Потрави до 11,0 m, оставив каретку в центре. Записываем, когда гик открылся, а twist вырос, не только когда сдвинут ползунок.", "Ease to 11.0 m with the car centered. Record after the boom opens and twist increases, not merely after moving the slider.", "Poluzuj do 11,0 m z wózkiem pośrodku. Zapisz po otwarciu bomu i wzroście skrętu, nie tylko po ruchu suwaka.", { es: "Lasca a 11,0 m con carro centrado. Registra cuando se abra la botavara y aumente la torsión.", fr: "Choque à 11,0 m, chariot centré. Enregistre quand la bôme s'ouvre et le vrillage augmente.", de: "Auf 11,0 m fieren, Traveller mittig. Erst bei geöffnetem Baum und mehr Twist erfassen.", it: "Lasca a 11,0 m con carrello al centro. Registra quando si apre il boma e aumenta il twist." }),
    compare: tp("Оставь 11,0 m. Перемести каретку на ветер и верни угол гика к исходному с точностью 1°. Подъем и twist должны отличаться от исходных.", "Keep 11.0 m. Move the car to windward and match the original boom angle within 1°. Rise and twist must differ from the baseline.", "Zostaw 11,0 m. Przesuń wózek na nawietrzną i odtwórz kąt bomu z dokładnością 1°. Uniesienie i skręt mają różnić się od początkowych.", { es: "Mantén 11,0 m. Lleva el carro a barlovento e iguala el ángulo inicial con margen de 1°. Elevación y torsión deben cambiar.", fr: "Garde 11,0 m. Remonte le chariot au vent et retrouve l'angle initial à 1° près. Montée et vrillage doivent différer.", de: "11,0 m beibehalten. Traveller nach Luv und Ausgangswinkel auf 1° treffen. Anstieg und Twist müssen anders sein.", it: "Mantieni 11,0 m. Carrello sopravvento, angolo iniziale entro 1°. Salita e twist devono essere diversi." }),
    answer: tp("Посмотри на записанные подъем и twist. Один и тот же угол сверху не фиксирует форму по высоте.", "Look at the recorded rise and twist. The same top-view angle does not fix the shape with height.", "Spójrz na zapisane uniesienie i skręt. Ten sam kąt z góry nie określa kształtu po wysokości.", { es: "Mira elevación y torsión registradas. El mismo ángulo superior no fija la forma en altura.", fr: "Observe montée et vrillage. Le même angle vu de dessus ne fixe pas la forme en hauteur.", de: "Sieh auf Anstieg und Twist. Gleicher Winkel von oben legt die Form über die Höhe nicht fest.", it: "Osserva salita e twist. Lo stesso angolo dall'alto non fissa la forma in altezza." }),
  };
  const step = ["baseline", "ease", "compare", "explain", "complete"].indexOf(study.phase) + 1;
  const rows = [study.baseline, study.eased, study.compared];
  const baseline = tp("Исходное", "Baseline", "Początek", { es: "Inicial", fr: "Initial", de: "Ausgang", it: "Iniziale" });
  const eased = tp("Потравили", "Eased", "Poluzowano", { es: "Lascado", fr: "Choqué", de: "Gefiert", it: "Lascata" });
  const compared = tp("Тот же угол", "Same angle", "Ten sam kąt", { es: "Mismo ángulo", fr: "Même angle", de: "Gleicher Winkel", it: "Stesso angolo" });
  return <section className="space-y-3 py-3" aria-label={title}>
    <h3 className="text-base font-semibold text-[var(--text-primary)]">{title} <span className="text-[var(--text-secondary)]">{Math.min(4, step)}/4</span></h3>
    {study.phase === "baseline" && <p className="text-sm leading-relaxed text-[var(--text-secondary)]">{tp("1. Не меняй настройки. Дождись стабилизации и запиши исходный угол, подъем и twist. Виды с кормы и 3D помогут увидеть форму.", "1. Keep the settings. Wait for stability, then record the initial angle, rise and twist. Rear and 3D views help you see the shape.", "1. Nie zmieniaj nastaw. Poczekaj i zapisz początkowy kąt, unoszenie i skręt. Widoki od rufy i 3D pokazują kształt.", { es: "1. Mantén los ajustes. Espera y registra ángulo, elevación y torsión iniciales. Observa desde popa y en 3D.", fr: "1. Garde les réglages. Attends puis note angle, montée et vrillage initiaux. Observe depuis l'arrière et en 3D.", de: "1. Einstellungen lassen. Stabilität abwarten, dann Winkel, Anstieg und Twist erfassen. Von achtern und in 3D betrachten.", it: "1. Mantieni i comandi. Attendi e registra angolo, salita e twist iniziali. Osserva da poppa e in 3D." })}</p>}
    {study.phase === "ease" && <p className="text-sm leading-relaxed text-[var(--text-secondary)]">2. {issue.ease}</p>}
    {study.phase === "compare" && <div className="space-y-2 text-sm leading-relaxed text-[var(--text-secondary)]"><p>3. {issue.compare}</p><p className="tabular-nums">{baseline}: {Math.abs(study.baseline!.yaw).toFixed(1)}°. {tp("На ветер", "To windward", "Na nawietrzną", { es: "A barlovento", fr: "Au vent", de: "Nach Luv", it: "Sopravvento" })}: {study.baseline!.yaw < 0 ? "+" : "-"}.</p></div>}
    {step < 4 && <>
      <p className="text-xs tabular-nums text-[var(--text-secondary)]">{tp("Стабильное состояние", "Stable state", "Stan stabilny", { es: "Estado estable", fr: "État stable", de: "Stabiler Zustand", it: "Stato stabile" })}: {(Math.floor(study.stableFor * 10) / 10).toFixed(1)}/3 s</p>
      <button className={button} onClick={record}>{tp("Записать наблюдение", "Record observation", "Zapisz obserwację", { es: "Registrar observación", fr: "Noter l'observation", de: "Beobachtung erfassen", it: "Registra osservazione" })}</button>
    </>}
    {study.baseline && <div className="overflow-x-auto">
      <table className="w-full text-left text-xs tabular-nums text-[var(--text-primary)]">
        <caption className="pb-2 text-left text-[var(--text-secondary)]">{tp("Наблюдения этого опыта", "Observations in this experiment", "Obserwacje w tym doświadczeniu", { es: "Observaciones del experimento", fr: "Observations de cette expérience", de: "Beobachtungen dieses Versuchs", it: "Osservazioni di questo esperimento" })}</caption>
        <thead><tr><th className="py-2" scope="col">{tp("Состояние", "State", "Stan", { es: "Estado", fr: "État", de: "Zustand", it: "Stato" })}</th><th scope="col">{tp("Гик", "Boom", "Bom", { es: "Bota.", fr: "Bôme", de: "Baum", it: "Boma" })}</th><th scope="col">{tp("Подъем", "Rise", "Wznios", { es: "Elev.", fr: "Montée", de: "Anstieg", it: "Salita" })}</th><th scope="col">Twist</th></tr></thead>
        <tbody>{rows.map((row, i) => row && <tr key={i} className="border-t border-[var(--border-subtle)]"><th className="py-2 font-normal" scope="row">{[baseline, eased, compared][i]}</th><td>{Math.abs(row.yaw).toFixed(1)}°</td><td>{row.rise.toFixed(1)}°</td><td>{row.twist.toFixed(1)}°</td></tr>)}</tbody>
      </table>
    </div>}
    {study.phase === "explain" && <fieldset className="space-y-2"><legend className="mb-2 text-sm text-[var(--text-primary)]">{tp("4. Почему при том же угле гика форма другая?", "4. Why is the shape different at the same boom angle?", "4. Dlaczego przy tym samym kącie kształt jest inny?", { es: "4. ¿Por qué cambia la forma con el mismo ángulo?", fr: "4. Pourquoi une autre forme au même angle ?", de: "4. Warum eine andere Form bei gleichem Winkel?", it: "4. Perché cambia la forma allo stesso angolo?" })}</legend>
      <button className={button} onClick={() => answer("angle-only")}>{tp("Это только ракурс камеры", "Only the camera angle changed", "Zmienił się tylko widok kamery", { es: "Solo cambió la cámara", fr: "Seule la caméra a changé", de: "Nur der Kamerawinkel änderte sich", it: "È cambiata solo la camera" })}</button>
      <button className={button} onClick={() => answer("shape")}>{tp("Шкот и каретка изменили подъем и twist", "Sheet and traveler changed rise and twist", "Szot i wózek zmieniły unoszenie i skręt", { es: "Escota y carro cambiaron elevación y torsión", fr: "Écoute et chariot ont changé montée et vrillage", de: "Schot und Traveller änderten Anstieg und Twist", it: "Scotta e carrello hanno cambiato salita e twist" })}</button>
    </fieldset>}
    {study.issue && <p role="status" className="text-sm leading-relaxed text-[var(--accent-cyan)]">{issue[study.issue]}</p>}
    {study.phase === "complete" && <p role="status" className="text-sm leading-relaxed text-[var(--text-primary)]">{tp("Опыт выполнен. Ты сохранил угол гика, но открыл верх грота. Значит, одного вида сверху мало: сравнивай форму с кормы и сбоку. Это наблюдение с помощником, не подтверждение самостоятельной работы на яхте. Перед выходом сохрани снимок через «Сохранение сессии».", "Experiment complete. You retained the boom angle but opened the upper sail. A top view alone is insufficient: compare the shape astern and from the side. This is an assisted observation, not proof of independent yacht handling. Before leaving, save a checkpoint under Session checkpoint.", "Doświadczenie ukończone. Kąt bomu pozostał podobny, lecz góra grota się otworzyła. Sam widok z góry nie wystarcza. Porównuj od rufy i z boku. To obserwacja z pomocą, nie potwierdzenie samodzielnej obsługi jachtu. Przed wyjściem zapisz wynik w sekcji Zapis sesji.", { es: "Experimento completo. Mantuviste el ángulo pero abriste la parte alta. Compara también desde popa y de lado. Es observación asistida, no prueba de manejo autónomo. Antes de salir, guarda en Guardar sesión.", fr: "Expérience terminée. Même angle, mais haut plus ouvert. Compare aussi depuis l'arrière et de côté. C'est une observation assistée, pas une preuve de manœuvre autonome. Avant de quitter, enregistre dans Sauvegarde de session.", de: "Versuch abgeschlossen. Gleicher Baumwinkel, aber oben offener. Auch von achtern und seitlich vergleichen. Dies ist unterstütztes Beobachten, kein Nachweis selbstständiger Yachtbedienung. Vor dem Verlassen unter Sitzung speichern sichern.", it: "Esperimento completato. Stesso angolo, parte alta più aperta. Confronta anche da poppa e di lato. È osservazione assistita, non prova di manovra autonoma. Prima di uscire salva in Salvataggio sessione." })}</p>}
    <div className="flex flex-wrap gap-2">
      <button className={button} onClick={start}>{tp("Начать заново", "Restart", "Zacznij od nowa", { es: "Reiniciar", fr: "Recommencer", de: "Neu starten", it: "Ricomincia" })}</button>
      <button className={button} onClick={cancel}>{tp("Закрыть опыт, оставить лодку", "Close experiment, keep boat", "Zamknij doświadczenie, zachowaj łódź", { es: "Cerrar sin reiniciar el barco", fr: "Fermer sans réinitialiser le bateau", de: "Versuch schließen, Boot behalten", it: "Chiudi senza azzerare la barca" })}</button>
    </div>
  </section>;
}
