// Generated by scripts/build-race-server.mjs. Do not edit by hand.

// src/lib/sailing-physics/wind.ts
var KN_TO_MPS = 0.514444;
var MPS_TO_KN = 1 / KN_TO_MPS;
var DEG_TO_RAD = Math.PI / 180;
var RAD_TO_DEG = 180 / Math.PI;
function twaFromCompass(trueWindDir, heading) {
  let twa = trueWindDir - heading;
  while (twa > 180) twa -= 360;
  while (twa <= -180) twa += 360;
  return twa;
}
function apparentWind(trueWindSpeedKn, twa, boatSpeedKn, leewayDeg = 0) {
  const tws = trueWindSpeedKn * KN_TO_MPS;
  const bs = boatSpeedKn * KN_TO_MPS;
  const twaRad = twa * DEG_TO_RAD;
  const windX = -tws * Math.sin(twaRad);
  const windY = -tws * Math.cos(twaRad);
  const leewayRad = leewayDeg * DEG_TO_RAD;
  const boatX = bs * Math.sin(leewayRad);
  const boatY = bs * Math.cos(leewayRad);
  const awX = windX - boatX;
  const awY = windY - boatY;
  const awsMps = Math.hypot(awX, awY);
  const awaRad = Math.atan2(-awX, -awY);
  const awa = awaRad * RAD_TO_DEG;
  return {
    vec: { x: awX, y: awY },
    aws: awsMps * MPS_TO_KN,
    awa
  };
}
function vmg(boatSpeedKn, twa) {
  return boatSpeedKn * Math.cos(twa * DEG_TO_RAD);
}

// src/lib/sailing-physics/aero.ts
function sailCl(aoaDeg, peakCl = 1.5) {
  const a = Math.abs(aoaDeg);
  if (a < 3) return a / 3 * 0.4;
  if (a < 12) return 0.4 + (a - 3) / 9 * (peakCl - 0.4);
  if (a < 18) return peakCl;
  if (a < 25) return peakCl - (a - 18) / 7 * (peakCl - 0.45);
  if (a < 45) return 0.45 - (a - 25) / 20 * 0.3;
  if (a < 90) return 0.15 + (a - 45) / 45 * 0.15;
  if (a < 135) return 0.3 - (a - 90) / 45 * 0.3;
  return 0;
}
function sailCd(aoaDeg) {
  const a = Math.abs(aoaDeg);
  if (a < 10) return 0.06 + a / 10 * 0.04;
  if (a < 25) return 0.1 + (a - 10) / 15 * 0.25;
  if (a < 90) return 0.35 + (a - 25) / 65 * 0.85;
  if (a < 180) return 1.2 - (a - 90) / 90 * 0.35;
  return 0.85;
}
function isStalled(aoaDeg, stallOnset = 20) {
  return Math.abs(aoaDeg) >= stallOnset;
}

// src/lib/sailing-physics/mainsail-shape.ts
function outhaulDepthFactor(ease, height) {
  const setting = Math.max(0, Math.min(1, ease ?? 0.5));
  const lower = Math.max(0, 1 - Math.max(0, height) / 0.6) ** 2;
  return 1 + 0.65 * (setting - 0.5) * lower;
}

// src/lib/sailing-physics/forces.ts
var RHO_AIR = 1.225;
function computeSectionForce(aw, awsMps, cfg, clMultiplier = 1, cdMultiplier = 1) {
  if (awsMps < 1e-4 || cfg.area < 1e-4) {
    return { drive: 0, side: 0, aoa: 0, stalled: false };
  }
  const angleRad = cfg.angleOff * DEG_TO_RAD;
  const chordX = cfg.side * Math.sin(angleRad);
  const chordY = -Math.cos(angleRad);
  const flowX = aw.x / awsMps;
  const flowY = aw.y / awsMps;
  let cosAngle = chordX * flowX + chordY * flowY;
  if (cosAngle > 1) cosAngle = 1;
  if (cosAngle < -1) cosAngle = -1;
  const aoa = Math.acos(cosAngle) * RAD_TO_DEG;
  let leewardX;
  let leewardY;
  if (cfg.side < 0) {
    leewardX = chordY;
    leewardY = -chordX;
  } else {
    leewardX = -chordY;
    leewardY = chordX;
  }
  const flowDotLeeward = flowX * leewardX + flowY * leewardY;
  const backed = flowDotLeeward < 0;
  const clRaw = sailCl(aoa, 1.5) * clMultiplier;
  const cl = backed ? -clRaw * 0.5 : clRaw;
  const cd = sailCd(aoa) * cdMultiplier;
  const stalled = isStalled(aoa, 18);
  const q = 0.5 * RHO_AIR * awsMps * awsMps;
  const liftMag = q * cfg.area * cl;
  const dragMag = q * cfg.area * cd;
  const liftCwX = flowY;
  const liftCwY = -flowX;
  const dotCw = liftCwX * leewardX + liftCwY * leewardY;
  let liftHatX;
  let liftHatY;
  if (dotCw >= 0) {
    liftHatX = liftCwX;
    liftHatY = liftCwY;
  } else {
    liftHatX = -flowY;
    liftHatY = flowX;
  }
  const fx = liftMag * liftHatX + dragMag * flowX;
  const fy = liftMag * liftHatY + dragMag * flowY;
  return {
    drive: fy,
    side: fx,
    aoa,
    stalled
  };
}
var MAX_SAIL_TWIST_DEG = 20;
function sectionTwistDegrees(twist, height) {
  return Math.max(0, Math.min(1, twist)) * MAX_SAIL_TWIST_DEG * Math.pow(height, 1.6);
}
function computeSailForce(aw, awsMps, cfg, clMultiplier = 1) {
  let drive = 0, side = 0, aoa = 0, stalledArea = 0;
  for (let i = 0; i < 5; i++) {
    const height = (i + 0.5) / 5;
    const weight = 2 * (1 - height) / 5;
    const depthDelta = outhaulDepthFactor(cfg.outhaulEase, height) - 1;
    const section = computeSectionForce(aw, awsMps, {
      ...cfg,
      area: cfg.area * weight,
      angleOff: cfg.angleOff + sectionTwistDegrees(cfg.twist, height),
      twist: 0
    }, clMultiplier * (1 + 0.8 * depthDelta), 1 + 1.2 * depthDelta);
    drive += section.drive;
    side += section.side;
    aoa += section.aoa * weight;
    if (section.stalled) stalledArea += weight;
  }
  return { drive, side, aoa, stalled: stalledArea >= 0.5 };
}
function slotMultiplier(args) {
  const { jibAoA, jibStalled, jibFurl01, jibAreaEffective, jibSide, mainSide } = args;
  if (jibAreaEffective < 1 || jibFurl01 > 0.8) return { mult: 1, health: 0.3 };
  if (jibSide !== mainSide) return { mult: 1, health: 0 };
  if (jibStalled) return { mult: 0.92, health: 0.2 };
  const a = Math.abs(jibAoA);
  if (a < 3) return { mult: 0.95, health: 0.3 };
  if (a < 20) {
    const peakness = 1 - Math.abs(a - 12) / 12;
    const mult = 1 + 0.15 * peakness;
    return { mult, health: 0.5 + 0.5 * peakness };
  }
  return { mult: 0.95, health: 0.2 };
}

// src/lib/sailing-physics/balance.ts
var G = 9.80665;
var KEEL_HEEL_EXP = 2;
function computeBalance(args) {
  const { fSideMainN, fSideJibN, mainCop, jibCop, boatSpeedKn, params: params2 } = args;
  const heelingMoment = fSideMainN * mainCop + fSideJibN * jibCop;
  const rightingCoeff = params2.displacement * G * params2.gm;
  const tanHeel = heelingMoment / Math.max(rightingCoeff, 1);
  const heelEquilibrium = Math.atan(tanHeel) * RAD_TO_DEG;
  const vMps = Math.max(boatSpeedKn * KN_TO_MPS, 0);
  const keelGrip = Math.pow(Math.max(Math.cos(heelEquilibrium * DEG_TO_RAD), 0.2), KEEL_HEEL_EXP);
  const denom = params2.keelK * keelGrip * (vMps + 0.5) * (vMps + 0.5);
  const totalSide = fSideMainN + fSideJibN;
  const leewayRadRaw = totalSide / denom;
  const leewayDegRaw = leewayRadRaw * RAD_TO_DEG;
  const leewayEquilibrium = Number.isFinite(leewayDegRaw) ? Math.max(-12, Math.min(12, leewayDegRaw)) : 0;
  return { heelEquilibrium, leewayEquilibrium };
}

// src/lib/sailing-physics/sail-plan.ts
var SAIL_PLAN = {
  main: { area: 45, height: 17, foot: 5.2, clewRise: 0.16 },
  jib: { area: 30, height: 16.1433333333, luffOffset: -5.8, clewRise: 1.05, roach: -0.14 }
};
var clampSailFraction = (value) => Math.max(0, Math.min(1, value));
var reefAreaFraction = (reef) => 1 - 0.65 * clampSailFraction(reef);
var jibAreaFraction = (furl) => 1 - clampSailFraction(furl);

// src/lib/sailing-physics/simulate.ts
function createInitialState(args) {
  const heading = args.heading ?? 0;
  let trueWindDir;
  if (typeof args.twa === "number") {
    trueWindDir = (heading + args.twa + 360) % 360;
  } else {
    trueWindDir = args.trueWindDir ?? 0;
  }
  return {
    trueWindDir,
    trueWindSpeed: args.tws,
    heading,
    boatSpeed: args.boatSpeed ?? 2,
    heel: 0,
    leeway: 0
  };
}
function sailAngleOff(sheet, minOff, maxOff) {
  const t = Math.max(0, Math.min(1, sheet));
  return minOff + (1 - t) * (maxOff - minOff);
}
function effectiveArea(fullArea, reduction01) {
  return fullArea * reefAreaFraction(reduction01);
}
function effectiveCop(fullCop, reduction01) {
  const r = Math.max(0, Math.min(1, reduction01));
  return fullCop * (1 - 0.35 * r);
}
function tick(state, controls, params2, dt, rig) {
  const twa = twaFromCompass(state.trueWindDir, state.heading);
  const aw = apparentWind(
    state.trueWindSpeed,
    twa,
    state.boatSpeed,
    state.leeway
  );
  const awsMps = aw.aws * KN_TO_MPS;
  const mainSideSign = rig?.main.side ?? (twa > 0 ? -1 : twa < 0 ? 1 : -1);
  const jibSideSign = rig?.jib.side ?? (controls.jibSide === -1 ? mainSideSign === 1 ? -1 : 1 : mainSideSign);
  const mainAngle = rig?.main.angleOff ?? sailAngleOff(controls.mainSheet, 0, params2.mainMaxOff);
  const jibAngle = rig?.jib.angleOff ?? sailAngleOff(controls.jibSheet, params2.jibMinOff, params2.jibMaxOff);
  const mainLoad = Math.max(0, Math.min(1, rig?.main.load ?? 1));
  const jibLoad = Math.max(0, Math.min(1, rig?.jib.load ?? 1));
  const mainArea = controls.mainHoisted === false ? 0 : effectiveArea(params2.mainArea, controls.reef);
  const jibArea = params2.jibArea * jibAreaFraction(controls.jibFurl);
  const jibCfg = {
    area: jibArea * jibLoad,
    angleOff: jibAngle,
    side: jibSideSign,
    twist: controls.jibTwist
  };
  const jibF = computeSailForce(aw.vec, awsMps, jibCfg, 1);
  const slot = slotMultiplier({
    jibAoA: jibF.aoa,
    jibStalled: jibF.stalled,
    jibFurl01: controls.jibFurl,
    jibAreaEffective: jibArea * jibLoad,
    jibSide: jibSideSign,
    mainSide: mainSideSign
  });
  const mainCfg = {
    area: mainArea * mainLoad,
    angleOff: mainAngle,
    side: mainSideSign,
    twist: controls.mainTwist,
    outhaulEase: rig?.main.outhaulEase
  };
  const mainF = computeSailForce(aw.vec, awsMps, mainCfg, slot.mult);
  const twaFromDead = 180 - Math.abs(twa);
  if (mainArea > 0 && jibSideSign === mainSideSign && twaFromDead < 45) {
    const blanketFactor = 0.4 + 0.6 * (twaFromDead / 45);
    jibF.drive *= blanketFactor;
    jibF.side *= blanketFactor;
  }
  const heelRad = Math.abs(state.heel) * Math.PI / 180;
  const heelSailFactor = Math.cos(heelRad);
  const mainSideEff = mainF.side * heelSailFactor;
  const jibSideEff = jibF.side * heelSailFactor;
  const mainDriveEff = mainF.drive * heelSailFactor;
  const jibDriveEff = jibF.drive * heelSailFactor;
  const balance = computeBalance({
    fSideMainN: mainSideEff,
    fSideJibN: jibSideEff,
    mainCop: effectiveCop(params2.mainCOP, controls.reef),
    // Roller furling narrows the jib along its full-height forestay. It does
    // not lower its head like a slab reef. Keep the reference pressure height
    // for this sectional model; area reduction already reduces the moment.
    jibCop: params2.jibCOP,
    boatSpeedKn: state.boatSpeed,
    params: params2
  });
  const tauHeel = 2;
  const tauLeeway = 4;
  const alphaHeel = 1 - Math.exp(-dt / tauHeel);
  const alphaLeeway = 1 - Math.exp(-dt / tauLeeway);
  const newHeel = state.heel + alphaHeel * (balance.heelEquilibrium - state.heel);
  const newLeeway = state.leeway + alphaLeeway * (balance.leewayEquilibrium - state.leeway);
  const bsMps = state.boatSpeed * KN_TO_MPS;
  const hullDragN = params2.hullDragK * bsMps * bsMps;
  const totalDriveN = mainDriveEff + jibDriveEff;
  const netN = totalDriveN - hullDragN;
  const accMps2 = netN / params2.surgeMass;
  let newBsMps = Math.max(0, bsMps + accMps2 * dt);
  const hullSpeedKn = 1.34 * Math.sqrt(params2.lwl * 3.281);
  const hullSpeedMps = hullSpeedKn * 1.25 * KN_TO_MPS;
  if (newBsMps > hullSpeedMps) newBsMps = hullSpeedMps;
  const newBsKn = newBsMps * MPS_TO_KN;
  const diag = {
    aws: aw.aws,
    awa: aw.awa,
    mainAoA: mainF.aoa,
    jibAoA: jibF.aoa,
    mainStalled: mainF.stalled,
    jibStalled: jibF.stalled,
    slotHealth: slot.health,
    drive: totalDriveN,
    side: mainF.side + jibF.side,
    vmg: vmg(newBsKn, twa)
  };
  const newState = {
    ...state,
    boatSpeed: newBsKn,
    heel: newHeel,
    leeway: newLeeway
  };
  return { state: newState, diag };
}

// src/lib/sailing-physics/boat.ts
var DEFAULT_BOAT = {
  displacement: 8e3,
  // kg, typical for 40 ft cruiser
  loa: 13.8554,
  // m, measured GLB hull length in metre units
  lwl: 12.2,
  // m. Hull speed = 1.34 * sqrt(lwl_ft) ~ 8.5 kn.
  mainArea: SAIL_PLAN.main.area,
  jibArea: SAIL_PLAN.jib.area,
  mainCOP: 7.5,
  // m above waterline (center of pressure ~40% up the main)
  jibCOP: 4.5,
  // m above waterline
  mainMaxOff: 85,
  // deg (boom can swing ~85 deg to leeward)
  jibMaxOff: 55,
  // deg
  jibMinOff: 5,
  // deg (hard sheeted, cannot go fully on centerline)
  gm: 1,
  // m. Metacentric height. Lower = tender, higher = stiff.
  hullDragK: 240,
  // D = hullDragK * v^2 (v in m/s, D in N).
  // Tuned so beam-reach steady state lands in [5, 6.5] kn.
  // Raised from 220 together with keelK: realistic leeway
  // stops bleeding apparent wind, so hull drag now carries
  // that resistance. Keeps the trimmed polar within 2% of
  // the old speeds on average (worst cell 3.9%), so race
  // times, missions and leaderboards do not move.
  // DECISIONS.md ADR-0002.
  keelK: 6e3,
  // Effective keel/hull side-force constant.
  // Used as: leeway_rad ~ F_side / (keelK * (bs_mps + 0.5)^2)
  // At 1500 close-hauled leeway sat on the 12 deg clamp at
  // every wind speed, so the clamp, not the keel, set it.
  // With the heel term in balance.ts, 6000 gives 3.3-4.6
  // deg close-hauled at normal heel, 1.1-1.8 on a beam reach
  // and 0.2-0.3 running (Dedekam p. 5: marked leeway upwind,
  // little or none downwind). Locked by polar.test.ts.
  surgeMass: 1e4
  // kg. Added mass of water moving with the hull raises
  // effective inertia above displacement alone.
};
function getBoatParams(overrides = {}) {
  return { ...DEFAULT_BOAT, ...overrides };
}

// src/lib/sailing-physics/polar.ts
var params = getBoatParams();
var clamp = (v) => Math.max(0, Math.min(1, v));
function trimForDrive(state, initial) {
  const controls = { ...initial };
  for (const step of [0.125, 0.025]) {
    for (const key of ["jibSheet", "mainSheet"]) {
      const centre = controls[key];
      let best = -Infinity;
      for (let i = -4; i <= 4; i++) {
        const value = step === 0.125 ? (i + 4) * step : clamp(centre + i * step);
        const drive = tick(state, { ...controls, [key]: value }, params, 0).diag.drive;
        if (drive > best) {
          best = drive;
          controls[key] = value;
        }
      }
    }
  }
  return controls;
}

// src/lib/race-physics.ts
var WORLD = { width: 800, height: 1200 };
var WIND_DIRECTION_BASE = 0;
var MAX_SPEED = 8;
var TURN_RATE = 22;
var ACCEL = 2.5;
var MARK_ROUND_DIST = 28;
var MIN_BOAT_SEPARATION = 22;
var UNITS_PER_KNOT_SECOND = 8;
var deg2rad = (d) => d * Math.PI / 180;
var rad2deg = (r) => r * 180 / Math.PI;
function normalizeAngle(deg) {
  return (deg % 360 + 360) % 360;
}
function angleDiff(a, b) {
  let d = normalizeAngle(b) - normalizeAngle(a);
  if (d > 180) d -= 360;
  if (d < -180) d += 360;
  return d;
}
function distance(a, b) {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
function bearing(a, b) {
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const rad = Math.atan2(dx, -dy);
  return (rad2deg(rad) + 360) % 360;
}
function segmentCrossed(prev, curr, a, b) {
  const ccw = (A, B, C) => (C.y - A.y) * (B.x - A.x) > (B.y - A.y) * (C.x - A.x);
  return ccw(a, prev, curr) !== ccw(b, prev, curr) && ccw(a, b, prev) !== ccw(a, b, curr);
}
function speedFactorFromTWA(twa) {
  const a = Math.abs(twa);
  if (a < 30) return 0;
  if (a < 45) return (a - 30) / 15 * 0.65;
  if (a < 90) return 0.65 + (a - 45) / 45 * 0.35;
  if (a < 160) return 1 - (a - 90) / 70 * 0.15;
  return 0.85 - (a - 160) / 20 * 0.25;
}
function calcTWA(heading, windDir = 0) {
  return (heading - windDir + 540) % 360 - 180;
}
function windAt(t, seed = 0) {
  const shift = Math.sin(t * (2 * Math.PI / 22) + seed * 0.37) * 6 + Math.sin(t * (2 * Math.PI / 7) + seed * 0.91) * 2;
  const gust = 1 + Math.sin(t * (2 * Math.PI / 9) + seed * 0.13) * 0.12 + Math.sin(t * (2 * Math.PI / 3.3) + seed * 0.71) * 0.05;
  return {
    dir: (WIND_DIRECTION_BASE + shift + 360) % 360,
    gust: Math.max(0.75, Math.min(1.25, gust))
  };
}
function stepBoat(boat, dt, windDir, gust, input, opts = {}) {
  const authority = Math.max(0, Math.min(1, boat.speed / 3));
  boat.heading = normalizeAngle(boat.heading + Math.max(-1, Math.min(1, input.turn)) * TURN_RATE * authority * dt);
  const params2 = getBoatParams();
  const state = {
    ...boat.physics ?? createInitialState({ tws: 12 }),
    heading: boat.heading,
    boatSpeed: boat.speed,
    trueWindDir: windDir,
    trueWindSpeed: 12 * (opts.windStrengthMul ?? 1) * gust
  };
  boat.trimClock = (boat.trimClock ?? 1) + dt;
  if (!boat.trim || boat.trimClock >= 0.5) {
    boat.trim = trimForDrive(state, boat.trim ?? { mainSheet: 0.4, jibSheet: 0.2, mainTwist: 0.35, jibTwist: 0.4, reef: 0, jibFurl: 0, jibSide: 1 });
    boat.trimClock = 0;
  }
  boat.physics = tick(state, boat.trim, params2, dt).state;
  boat.speed = boat.physics.boatSpeed;
  const rad = deg2rad(boat.heading + boat.physics.leeway);
  boat.pos.x += Math.sin(rad) * boat.speed * UNITS_PER_KNOT_SECOND * dt;
  boat.pos.y -= Math.cos(rad) * boat.speed * UNITS_PER_KNOT_SECOND * dt;
  boat.pos.x = Math.max(20, Math.min(WORLD.width - 20, boat.pos.x));
  boat.pos.y = Math.max(20, Math.min(WORLD.height - 20, boat.pos.y));
}
var FULL_BUMP_CLOSING_KN = 1;
function groundVelocity(boat) {
  const rad = deg2rad(boat.heading + (boat.physics?.leeway ?? 0));
  return { x: Math.sin(rad) * boat.speed, y: -Math.cos(rad) * boat.speed };
}
function resolveCollisions(boats, dt = 1 / 20) {
  for (let i = 0; i < boats.length; i++) {
    for (let j = i + 1; j < boats.length; j++) {
      const a = boats[i];
      const b = boats[j];
      if (a.lapDone >= 2 || b.lapDone >= 2) continue;
      const dx = b.pos.x - a.pos.x;
      const dy = b.pos.y - a.pos.y;
      const d = Math.hypot(dx, dy);
      if (d < MIN_BOAT_SEPARATION) {
        const overlap = (MIN_BOAT_SEPARATION - d) / 2;
        const nx = d > 1e-3 ? dx / d : 1;
        const ny = d > 1e-3 ? dy / d : 0;
        a.pos.x -= nx * overlap;
        a.pos.y -= ny * overlap;
        b.pos.x += nx * overlap;
        b.pos.y += ny * overlap;
        const va = groundVelocity(a), vb = groundVelocity(b);
        const closing = (va.x - vb.x) * nx + (va.y - vb.y) * ny;
        const share = Math.max(0, Math.min(1, closing / FULL_BUMP_CLOSING_KN));
        if (share > 0) {
          const damp = Math.exp(-1.67 * dt * share);
          a.speed *= damp;
          b.speed *= damp;
        }
      }
    }
  }
}
function makeStandardCourse() {
  const cx = WORLD.width / 2;
  const startY = WORLD.height - 150;
  const windwardY = 180;
  const startLine = {
    a: { x: cx - 80, y: startY },
    b: { x: cx + 80, y: startY }
  };
  return {
    marks: [
      { pos: { x: cx, y: windwardY }, radius: 14, label: "Windward", type: "windward" },
      { pos: startLine.a, radius: 10, label: "Start L", type: "start" },
      { pos: startLine.b, radius: 10, label: "Start R", type: "start" }
    ],
    startLine,
    finishLine: startLine
  };
}
function updateLap(boat, prevPos, course, raceTime) {
  if (!boat.started) {
    if (prevPos.y > boat.pos.y && segmentCrossed(prevPos, boat.pos, course.startLine.a, course.startLine.b)) boat.started = true;
    else return null;
  }
  if (boat.lapDone === 0) {
    const m = course.marks[0];
    const inner = m.radius + MIN_BOAT_SEPARATION / 2;
    const outer = inner + 70;
    const x = m.pos.x, y = m.pos.y;
    const phase = boat.roundPhase ?? 0;
    if (phase === 0 && boat.pos.y < prevPos.y && segmentCrossed(prevPos, boat.pos, { x: x + inner, y }, { x: x + outer, y })) boat.roundPhase = 1;
    else if (phase === 1 && boat.pos.x < prevPos.x && segmentCrossed(prevPos, boat.pos, { x, y: y - inner }, { x, y: y - outer })) boat.roundPhase = 2;
    else if (phase === 2 && boat.pos.y > prevPos.y && segmentCrossed(prevPos, boat.pos, { x: x - inner, y }, { x: x - outer, y })) {
      boat.lapDone = 1;
      return "mark";
    }
  } else if (boat.lapDone === 1 && prevPos.y < boat.pos.y && segmentCrossed(prevPos, boat.pos, course.finishLine.a, course.finishLine.b)) {
    boat.lapDone = 2;
    boat.finishTime = raceTime;
    return "finish";
  }
  return null;
}
function raceWaypoint(boat, course) {
  if (!boat.started) {
    const y = course.startLine.a.y;
    if (boat.pos.y < y) boat.returningToStart = true;
    if (boat.pos.y > y + 35) boat.returningToStart = false;
    return { x: (course.startLine.a.x + course.startLine.b.x) / 2, y: y + (boat.returningToStart ? 60 : -60) };
  }
  if (boat.lapDone > 0) return { x: (course.finishLine.a.x + course.finishLine.b.x) / 2, y: course.finishLine.a.y + 30 };
  const m = course.marks[0].pos;
  const r = course.marks[0].radius + MIN_BOAT_SEPARATION / 2 + 35;
  if ((boat.roundPhase ?? 0) === 0) return { x: m.x + r, y: m.y - r };
  if (boat.roundPhase === 1) return { x: m.x - r, y: m.y - r };
  return { x: m.x - r, y: m.y + r };
}
var AUTOPILOT = {
  closeHauled: 45,
  // true wind angle sailed upwind, deg
  lookahead: 40,
  // path-following lookahead, world units
  loopRadius: 80,
  // rounding loop: passes G0 72 east, G1 45 north, G2 72 west of the mark
  loopDrop: 35,
  // rounding loop centre below the mark
  legMax: 450,
  // stadium legs: at most this long...
  legShare: 0.55,
  // ...and at most this share of the mark-to-line distance
  finalMax: 150,
  // last stretch of the climb sailed straight up the leg...
  finalShare: 0.35,
  // ...capped at this share of the mark-to-line distance
  radiusGrowth: 1.15,
  // turning circle grows as the boat bears away and speeds up
  shedHysteresis: 0.6,
  // kn below the target speed before sailing freely again
  shedMin: 2.5,
  // kn: too slow to keep pointing up the last stretch
  featherSlow: 12,
  // deg off the wind while shedding speed near the target
  featherFast: 3,
  // deg off the wind while well above it
  fastMargin: 0.8,
  // kn above the target speed that counts as "well above"
  featherGain: 0.4,
  // extra degrees per unit off the leg, to get back onto it
  featherMax: 24,
  featherBand: 12,
  // units off the leg before switching the feathering side
  band: { top: 12, slope: 0.25, max: 60 },
  // tacking corridor half-width on the climb
  startBand: 40,
  // tacking corridor half-width below the start line
  loopBand: 30,
  // tacking corridor half-width on the start and finish loops
  tackMinSpeed: 2,
  // kn: no tack below this
  stallSpeed: 2.2,
  // kn: below this, bear away from close to the wind (a bumped boat must not stop head to wind)
  dip: { drop: 30, minR: 70, maxR: 100, slack: 25 },
  finishLoop: { drop: 50, radius: 80 },
  finishLanes: 7,
  finishLaneMargin: 25
  // units kept clear of each end of the finish line
};
var RADIUS_PER_KNOT = UNITS_PER_KNOT_SECOND / deg2rad(TURN_RATE);
function onCircle(p, c, r, ccw) {
  const phi = bearing(c, p), d = distance(p, c);
  return ccw ? { tangent: normalizeAngle(phi - 90), right: d - r } : { tangent: normalizeAngle(phi + 90), right: r - d };
}
function onVertical(p, x, north) {
  return north ? { tangent: 0, right: p.x - x } : { tangent: 180, right: x - p.x };
}
function laneOf(id, lanes) {
  let h = 5381;
  for (let i = 0; i < id.length; i++) h = (h * 33 ^ id.charCodeAt(i)) >>> 0;
  return h % lanes / (lanes - 1) * 2 - 1;
}
function raceAutopilotTurn(boat, course, windDir) {
  const A = AUTOPILOT, p = boat.pos;
  if (!boat.autopilot || boat.lapDone < boat.autopilot.lap) boat.autopilot = { lap: boat.lapDone };
  const st = boat.autopilot;
  st.lap = boat.lapDone;
  const v = boat.speed > 0.05 ? boat.speed : 0;
  const line = boat.lapDone > 0 ? course.finishLine : course.startLine;
  const cx = (line.a.x + line.b.x) / 2, ly = line.a.y, half = Math.abs(line.b.x - line.a.x) / 2;
  const mark = course.marks[0].pos;
  const targetSpeed = A.loopRadius / (RADIUS_PER_KNOT * A.radiusGrowth);
  let fix;
  let band = 0;
  let forceTack = 0;
  let freeOverTop = false;
  if (!boat.started) {
    const below = p.y > ly;
    if (below && Math.abs(p.x - cx) < half - 10 && !st.dip) {
      fix = onVertical(p, cx, true);
      band = A.startBand;
    } else {
      if (!st.dip) {
        const twa = calcTWA(boat.heading, windDir);
        const ccw2 = Math.abs(twa) > 150 ? p.x < cx : twa < 0;
        const r2 = v > 0 ? Math.max(A.dip.minR, Math.min(A.dip.maxR, RADIUS_PER_KNOT * Math.max(v, 3))) : A.dip.maxR;
        st.dip = { ccw: ccw2, r: r2, x: p.x + (ccw2 ? -1 : 1) * r2 * Math.abs(Math.cos(deg2rad(boat.heading))) };
      }
      const { ccw, r } = st.dip, side = ccw ? -1 : 1;
      const w = Math.sqrt(Math.max(0, r * r - A.dip.drop * A.dip.drop));
      const x = Math.max(cx + side * w - A.dip.slack, Math.min(cx + side * w + A.dip.slack, st.dip.x));
      fix = onCircle(p, { x, y: ly + A.dip.drop }, r, ccw);
      if (below) {
        band = A.loopBand;
        forceTack = ccw ? -1 : 1;
      }
    }
  } else if (boat.lapDone === 0) {
    st.dip = void 0;
    const c = { x: mark.x, y: mark.y + A.loopDrop }, r = A.loopRadius;
    const room = Math.max(0, course.startLine.a.y - c.y);
    const leg = Math.min(A.legMax, A.legShare * room);
    if (!st.down && p.y <= c.y && p.x < c.x - r / 2) st.down = true;
    else if (st.down && p.y >= c.y + leg && p.x > c.x) st.down = false;
    const climbing = !st.down && p.y > c.y;
    if (!st.down) fix = p.y <= c.y ? onCircle(p, c, r, true) : onVertical(p, c.x + r, true);
    else fix = p.y >= c.y + leg ? onCircle(p, { x: c.x, y: c.y + leg }, r, true) : onVertical(p, c.x - r, false);
    if (climbing) band = Math.min(A.band.max, Math.max(A.band.top, A.band.slope * (p.y - c.y)));
    if (!st.down && p.y <= c.y) freeOverTop = true;
    const toTop = p.y - c.y;
    if (climbing && toTop < Math.min(A.finalMax, A.finalShare * room)) st.shed = v === 0 || v > A.shedMin;
    else if (climbing && v > 0 && toTop < leg) {
      if (v > targetSpeed) st.shed = true;
      else if (v < targetSpeed - A.shedHysteresis) st.shed = false;
    } else st.shed = false;
  } else {
    if (p.y > ly + 5 && !st.finishLoop) st.finishLoop = { ccw: p.x >= cx };
    if (st.finishLoop) {
      fix = onCircle(p, { x: cx, y: ly - A.finishLoop.drop }, A.finishLoop.radius, st.finishLoop.ccw);
      band = A.loopBand;
    } else fix = onVertical(p, cx + laneOf(boat.id, A.finishLanes) * Math.max(0, half - A.finishLaneMargin), false);
  }
  const slow = v > 0 && v < A.tackMinSpeed;
  if (st.tack === void 0) st.tack = calcTWA(boat.heading, windDir) >= 0 ? 1 : -1;
  const tackTo = (side) => {
    if (!slow) st.tack = side;
  };
  let desired = normalizeAngle(fix.tangent - rad2deg(Math.atan2(fix.right, A.lookahead)));
  if (st.shed) {
    if (fix.right > A.featherBand) tackTo(-1);
    else if (fix.right < -A.featherBand) tackTo(1);
    const off = Math.max(0, st.tack === -1 ? fix.right : -fix.right);
    const base = v > targetSpeed + A.fastMargin ? A.featherFast : A.featherSlow;
    desired = normalizeAngle(windDir + st.tack * Math.min(A.featherMax, base + A.featherGain * off));
  } else {
    const twa = calcTWA(desired, windDir);
    if (band > 0 && Math.abs(calcTWA(fix.tangent, windDir)) < A.closeHauled + 5) {
      if (forceTack) tackTo(forceTack);
      else if (fix.right > band) tackTo(-1);
      else if (fix.right < -band) tackTo(1);
      desired = normalizeAngle(windDir + st.tack * A.closeHauled);
    } else if (Math.abs(twa) < A.closeHauled && !freeOverTop) {
      if (twa > A.closeHauled - 5 && st.tack === -1) tackTo(1);
      else if (twa < -(A.closeHauled - 5) && st.tack === 1) tackTo(-1);
      desired = normalizeAngle(windDir + st.tack * A.closeHauled);
    } else if (Math.abs(twa) >= A.closeHauled) tackTo(twa >= 0 ? 1 : -1);
  }
  if (v > 0 && v < A.stallSpeed && Math.abs(calcTWA(desired, windDir)) < 25) desired = normalizeAngle(windDir + st.tack * A.closeHauled);
  return Math.max(-1, Math.min(1, angleDiff(boat.heading, desired) / 12));
}
export {
  ACCEL,
  FULL_BUMP_CLOSING_KN,
  MARK_ROUND_DIST,
  MAX_SPEED,
  MIN_BOAT_SEPARATION,
  TURN_RATE,
  UNITS_PER_KNOT_SECOND,
  WIND_DIRECTION_BASE,
  WORLD,
  angleDiff,
  bearing,
  calcTWA,
  deg2rad,
  distance,
  makeStandardCourse,
  normalizeAngle,
  raceAutopilotTurn,
  raceWaypoint,
  rad2deg,
  resolveCollisions,
  segmentCrossed,
  speedFactorFromTWA,
  stepBoat,
  updateLap,
  windAt
};
