// Generated by scripts/build-race-server.mjs. Do not edit by hand.

// src/lib/sailing-physics/wind.ts
var KN_TO_MPS = 0.514444;
var MPS_TO_KN = 1 / KN_TO_MPS;
var DEG_TO_RAD = Math.PI / 180;
var RAD_TO_DEG = 180 / Math.PI;
function twaFromCompass(trueWindDir, heading) {
  let twa = trueWindDir - heading;
  while (twa > 180) twa -= 360;
  while (twa <= -180) twa += 360;
  return twa;
}
function apparentWind(trueWindSpeedKn, twa, boatSpeedKn, leewayDeg = 0) {
  const tws = trueWindSpeedKn * KN_TO_MPS;
  const bs = boatSpeedKn * KN_TO_MPS;
  const twaRad = twa * DEG_TO_RAD;
  const windX = -tws * Math.sin(twaRad);
  const windY = -tws * Math.cos(twaRad);
  const leewayRad = leewayDeg * DEG_TO_RAD;
  const boatX = bs * Math.sin(leewayRad);
  const boatY = bs * Math.cos(leewayRad);
  const awX = windX - boatX;
  const awY = windY - boatY;
  const awsMps = Math.hypot(awX, awY);
  const awaRad = Math.atan2(-awX, -awY);
  const awa = awaRad * RAD_TO_DEG;
  return {
    vec: { x: awX, y: awY },
    aws: awsMps * MPS_TO_KN,
    awa
  };
}
function vmg(boatSpeedKn, twa) {
  return boatSpeedKn * Math.cos(twa * DEG_TO_RAD);
}

// src/lib/sailing-physics/aero.ts
function sailCl(aoaDeg, peakCl = 1.5) {
  const a = Math.abs(aoaDeg);
  if (a < 3) return a / 3 * 0.4;
  if (a < 12) return 0.4 + (a - 3) / 9 * (peakCl - 0.4);
  if (a < 18) return peakCl;
  if (a < 25) return peakCl - (a - 18) / 7 * (peakCl - 0.45);
  if (a < 45) return 0.45 - (a - 25) / 20 * 0.3;
  if (a < 90) return 0.15 + (a - 45) / 45 * 0.15;
  if (a < 135) return 0.3 - (a - 90) / 45 * 0.3;
  return 0;
}
function sailCd(aoaDeg) {
  const a = Math.abs(aoaDeg);
  if (a < 10) return 0.06 + a / 10 * 0.04;
  if (a < 25) return 0.1 + (a - 10) / 15 * 0.25;
  if (a < 90) return 0.35 + (a - 25) / 65 * 0.85;
  if (a < 180) return 1.2 - (a - 90) / 90 * 0.35;
  return 0.85;
}
function isStalled(aoaDeg, stallOnset = 20) {
  return Math.abs(aoaDeg) >= stallOnset;
}

// src/lib/sailing-physics/forces.ts
var RHO_AIR = 1.225;
function computeSectionForce(aw, awsMps, cfg, clMultiplier = 1) {
  if (awsMps < 1e-4 || cfg.area < 1e-4) {
    return { drive: 0, side: 0, aoa: 0, stalled: false };
  }
  const angleRad = cfg.angleOff * DEG_TO_RAD;
  const chordX = cfg.side * Math.sin(angleRad);
  const chordY = -Math.cos(angleRad);
  const flowX = aw.x / awsMps;
  const flowY = aw.y / awsMps;
  let cosAngle = chordX * flowX + chordY * flowY;
  if (cosAngle > 1) cosAngle = 1;
  if (cosAngle < -1) cosAngle = -1;
  const aoa = Math.acos(cosAngle) * RAD_TO_DEG;
  let leewardX;
  let leewardY;
  if (cfg.side < 0) {
    leewardX = chordY;
    leewardY = -chordX;
  } else {
    leewardX = -chordY;
    leewardY = chordX;
  }
  const flowDotLeeward = flowX * leewardX + flowY * leewardY;
  const backed = flowDotLeeward < 0;
  const clRaw = sailCl(aoa, 1.5) * clMultiplier;
  const cl = backed ? -clRaw * 0.5 : clRaw;
  const cd = sailCd(aoa);
  const stalled = isStalled(aoa, 18);
  const q = 0.5 * RHO_AIR * awsMps * awsMps;
  const liftMag = q * cfg.area * cl;
  const dragMag = q * cfg.area * cd;
  const liftCwX = flowY;
  const liftCwY = -flowX;
  const dotCw = liftCwX * leewardX + liftCwY * leewardY;
  let liftHatX;
  let liftHatY;
  if (dotCw >= 0) {
    liftHatX = liftCwX;
    liftHatY = liftCwY;
  } else {
    liftHatX = -flowY;
    liftHatY = flowX;
  }
  const fx = liftMag * liftHatX + dragMag * flowX;
  const fy = liftMag * liftHatY + dragMag * flowY;
  return {
    drive: fy,
    side: fx,
    aoa,
    stalled
  };
}
var MAX_SAIL_TWIST_DEG = 20;
function sectionTwistDegrees(twist, height) {
  return Math.max(0, Math.min(1, twist)) * MAX_SAIL_TWIST_DEG * Math.pow(height, 1.6);
}
function computeSailForce(aw, awsMps, cfg, clMultiplier = 1) {
  let drive = 0, side = 0, aoa = 0, stalledArea = 0;
  for (let i = 0; i < 5; i++) {
    const height = (i + 0.5) / 5;
    const weight = 2 * (1 - height) / 5;
    const section = computeSectionForce(aw, awsMps, {
      ...cfg,
      area: cfg.area * weight,
      angleOff: cfg.angleOff + sectionTwistDegrees(cfg.twist, height),
      twist: 0
    }, clMultiplier);
    drive += section.drive;
    side += section.side;
    aoa += section.aoa * weight;
    if (section.stalled) stalledArea += weight;
  }
  return { drive, side, aoa, stalled: stalledArea >= 0.5 };
}
function slotMultiplier(args) {
  const { jibAoA, jibStalled, jibFurl01, jibAreaEffective, jibSide, mainSide } = args;
  if (jibAreaEffective < 1 || jibFurl01 > 0.8) return { mult: 1, health: 0.3 };
  if (jibSide !== mainSide) return { mult: 1, health: 0 };
  if (jibStalled) return { mult: 0.92, health: 0.2 };
  const a = Math.abs(jibAoA);
  if (a < 3) return { mult: 0.95, health: 0.3 };
  if (a < 20) {
    const peakness = 1 - Math.abs(a - 12) / 12;
    const mult = 1 + 0.15 * peakness;
    return { mult, health: 0.5 + 0.5 * peakness };
  }
  return { mult: 0.95, health: 0.2 };
}

// src/lib/sailing-physics/balance.ts
var G = 9.80665;
function computeBalance(args) {
  const { fSideMainN, fSideJibN, mainCop, jibCop, boatSpeedKn, params: params2 } = args;
  const heelingMoment = fSideMainN * mainCop + fSideJibN * jibCop;
  const rightingCoeff = params2.displacement * G * params2.gm;
  const tanHeel = heelingMoment / Math.max(rightingCoeff, 1);
  const heelEquilibrium = Math.atan(tanHeel) * RAD_TO_DEG;
  const vMps = Math.max(boatSpeedKn * KN_TO_MPS, 0);
  const denom = params2.keelK * (vMps + 0.5) * (vMps + 0.5);
  const totalSide = fSideMainN + fSideJibN;
  const leewayRadRaw = totalSide / denom;
  const leewayDegRaw = leewayRadRaw * RAD_TO_DEG;
  const leewayEquilibrium = Math.max(-12, Math.min(12, leewayDegRaw));
  void DEG_TO_RAD;
  return { heelEquilibrium, leewayEquilibrium };
}

// src/lib/sailing-physics/sail-plan.ts
var SAIL_PLAN = {
  main: { area: 45, height: 17, foot: 5.2, clewRise: 0.16 },
  jib: { area: 30, height: 16.1433333333, luffOffset: -5.8, clewRise: 1.05, roach: -0.14 }
};
var clampSailFraction = (value) => Math.max(0, Math.min(1, value));
var reefAreaFraction = (reef) => 1 - 0.65 * clampSailFraction(reef);
var jibAreaFraction = (furl) => 1 - clampSailFraction(furl);

// src/lib/sailing-physics/simulate.ts
function createInitialState(args) {
  const heading = args.heading ?? 0;
  let trueWindDir;
  if (typeof args.twa === "number") {
    trueWindDir = (heading + args.twa + 360) % 360;
  } else {
    trueWindDir = args.trueWindDir ?? 0;
  }
  return {
    trueWindDir,
    trueWindSpeed: args.tws,
    heading,
    boatSpeed: args.boatSpeed ?? 2,
    heel: 0,
    leeway: 0
  };
}
function sailAngleOff(sheet, minOff, maxOff) {
  const t = Math.max(0, Math.min(1, sheet));
  return minOff + (1 - t) * (maxOff - minOff);
}
function effectiveArea(fullArea, reduction01) {
  return fullArea * reefAreaFraction(reduction01);
}
function effectiveCop(fullCop, reduction01) {
  const r = Math.max(0, Math.min(1, reduction01));
  return fullCop * (1 - 0.35 * r);
}
function tick(state, controls, params2, dt) {
  const twa = twaFromCompass(state.trueWindDir, state.heading);
  const aw = apparentWind(
    state.trueWindSpeed,
    twa,
    state.boatSpeed,
    state.leeway
  );
  const awsMps = aw.aws * KN_TO_MPS;
  const mainSideSign = twa > 0 ? -1 : twa < 0 ? 1 : -1;
  const jibSideSign = controls.jibSide === -1 ? mainSideSign === 1 ? -1 : 1 : mainSideSign;
  const mainAngle = sailAngleOff(controls.mainSheet, 0, params2.mainMaxOff);
  const jibAngle = sailAngleOff(controls.jibSheet, params2.jibMinOff, params2.jibMaxOff);
  const mainArea = controls.mainHoisted === false ? 0 : effectiveArea(params2.mainArea, controls.reef);
  const jibArea = params2.jibArea * jibAreaFraction(controls.jibFurl);
  const jibCfg = {
    area: jibArea,
    angleOff: jibAngle,
    side: jibSideSign,
    twist: controls.jibTwist
  };
  const jibF = computeSailForce(aw.vec, awsMps, jibCfg, 1);
  const slot = slotMultiplier({
    jibAoA: jibF.aoa,
    jibStalled: jibF.stalled,
    jibFurl01: controls.jibFurl,
    jibAreaEffective: jibArea,
    jibSide: jibSideSign,
    mainSide: mainSideSign
  });
  const mainCfg = {
    area: mainArea,
    angleOff: mainAngle,
    side: mainSideSign,
    twist: controls.mainTwist
  };
  const mainF = computeSailForce(aw.vec, awsMps, mainCfg, slot.mult);
  const twaFromDead = 180 - Math.abs(twa);
  if (mainArea > 0 && jibSideSign === mainSideSign && twaFromDead < 45) {
    const blanketFactor = 0.4 + 0.6 * (twaFromDead / 45);
    jibF.drive *= blanketFactor;
    jibF.side *= blanketFactor;
  }
  const heelRad = Math.abs(state.heel) * Math.PI / 180;
  const heelSailFactor = Math.cos(heelRad);
  const mainSideEff = mainF.side * heelSailFactor;
  const jibSideEff = jibF.side * heelSailFactor;
  const mainDriveEff = mainF.drive * heelSailFactor;
  const jibDriveEff = jibF.drive * heelSailFactor;
  const balance = computeBalance({
    fSideMainN: mainSideEff,
    fSideJibN: jibSideEff,
    mainCop: effectiveCop(params2.mainCOP, controls.reef),
    jibCop: effectiveCop(params2.jibCOP, controls.jibFurl),
    boatSpeedKn: state.boatSpeed,
    params: params2
  });
  const tauHeel = 2;
  const tauLeeway = 4;
  const alphaHeel = 1 - Math.exp(-dt / tauHeel);
  const alphaLeeway = 1 - Math.exp(-dt / tauLeeway);
  const newHeel = state.heel + alphaHeel * (balance.heelEquilibrium - state.heel);
  const newLeeway = state.leeway + alphaLeeway * (balance.leewayEquilibrium - state.leeway);
  const bsMps = state.boatSpeed * KN_TO_MPS;
  const hullDragN = params2.hullDragK * bsMps * bsMps;
  const totalDriveN = mainDriveEff + jibDriveEff;
  const netN = totalDriveN - hullDragN;
  const accMps2 = netN / params2.surgeMass;
  let newBsMps = Math.max(0, bsMps + accMps2 * dt);
  const hullSpeedKn = 1.34 * Math.sqrt(params2.lwl * 3.281);
  const hullSpeedMps = hullSpeedKn * 1.25 * KN_TO_MPS;
  if (newBsMps > hullSpeedMps) newBsMps = hullSpeedMps;
  const newBsKn = newBsMps * MPS_TO_KN;
  const diag = {
    aws: aw.aws,
    awa: aw.awa,
    mainAoA: mainF.aoa,
    jibAoA: jibF.aoa,
    mainStalled: mainF.stalled,
    jibStalled: jibF.stalled,
    slotHealth: slot.health,
    drive: totalDriveN,
    side: mainF.side + jibF.side,
    vmg: vmg(newBsKn, twa)
  };
  const newState = {
    ...state,
    boatSpeed: newBsKn,
    heel: newHeel,
    leeway: newLeeway
  };
  return { state: newState, diag };
}

// src/lib/sailing-physics/boat.ts
var DEFAULT_BOAT = {
  displacement: 8e3,
  // kg, typical for 40 ft cruiser
  loa: 13.8554,
  // m, measured GLB hull length in metre units
  lwl: 12.2,
  // m. Hull speed = 1.34 * sqrt(lwl_ft) ~ 8.5 kn.
  mainArea: SAIL_PLAN.main.area,
  jibArea: SAIL_PLAN.jib.area,
  mainCOP: 7.5,
  // m above waterline (center of pressure ~40% up the main)
  jibCOP: 4.5,
  // m above waterline
  mainMaxOff: 85,
  // deg (boom can swing ~85 deg to leeward)
  jibMaxOff: 55,
  // deg
  jibMinOff: 5,
  // deg (hard sheeted, cannot go fully on centerline)
  gm: 1,
  // m. Metacentric height. Lower = tender, higher = stiff.
  hullDragK: 220,
  // D = hullDragK * v^2 (v in m/s, D in N).
  // Tuned so beam-reach steady state lands in [5, 6.5] kn.
  keelK: 1500,
  // Effective keel/hull side-force constant.
  // Used as: leeway_rad ~ F_side / (keelK * (bs_mps + 0.5)^2)
  surgeMass: 1e4
  // kg. Added mass of water moving with the hull raises
  // effective inertia above displacement alone.
};
function getBoatParams(overrides = {}) {
  return { ...DEFAULT_BOAT, ...overrides };
}

// src/lib/sailing-physics/polar.ts
var params = getBoatParams();
var clamp = (v) => Math.max(0, Math.min(1, v));
function trimForDrive(state, initial) {
  const controls = { ...initial };
  for (const step of [0.125, 0.025]) {
    for (const key of ["jibSheet", "mainSheet"]) {
      const centre = controls[key];
      let best = -Infinity;
      for (let i = -4; i <= 4; i++) {
        const value = step === 0.125 ? (i + 4) * step : clamp(centre + i * step);
        const drive = tick(state, { ...controls, [key]: value }, params, 0).diag.drive;
        if (drive > best) {
          best = drive;
          controls[key] = value;
        }
      }
    }
  }
  return controls;
}

// src/lib/race-physics.ts
var WORLD = { width: 800, height: 1200 };
var WIND_DIRECTION_BASE = 0;
var MAX_SPEED = 8;
var TURN_RATE = 22;
var ACCEL = 2.5;
var MARK_ROUND_DIST = 28;
var MIN_BOAT_SEPARATION = 22;
var deg2rad = (d) => d * Math.PI / 180;
var rad2deg = (r) => r * 180 / Math.PI;
function normalizeAngle(deg) {
  return (deg % 360 + 360) % 360;
}
function angleDiff(a, b) {
  let d = normalizeAngle(b) - normalizeAngle(a);
  if (d > 180) d -= 360;
  if (d < -180) d += 360;
  return d;
}
function distance(a, b) {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
function bearing(a, b) {
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const rad = Math.atan2(dx, -dy);
  return (rad2deg(rad) + 360) % 360;
}
function segmentCrossed(prev, curr, a, b) {
  const ccw = (A, B, C) => (C.y - A.y) * (B.x - A.x) > (B.y - A.y) * (C.x - A.x);
  return ccw(a, prev, curr) !== ccw(b, prev, curr) && ccw(a, b, prev) !== ccw(a, b, curr);
}
function speedFactorFromTWA(twa) {
  const a = Math.abs(twa);
  if (a < 30) return 0;
  if (a < 45) return (a - 30) / 15 * 0.65;
  if (a < 90) return 0.65 + (a - 45) / 45 * 0.35;
  if (a < 160) return 1 - (a - 90) / 70 * 0.15;
  return 0.85 - (a - 160) / 20 * 0.25;
}
function calcTWA(heading, windDir = 0) {
  return (heading - windDir + 540) % 360 - 180;
}
function windAt(t, seed = 0) {
  const shift = Math.sin(t * (2 * Math.PI / 22) + seed * 0.37) * 6 + Math.sin(t * (2 * Math.PI / 7) + seed * 0.91) * 2;
  const gust = 1 + Math.sin(t * (2 * Math.PI / 9) + seed * 0.13) * 0.12 + Math.sin(t * (2 * Math.PI / 3.3) + seed * 0.71) * 0.05;
  return {
    dir: (WIND_DIRECTION_BASE + shift + 360) % 360,
    gust: Math.max(0.75, Math.min(1.25, gust))
  };
}
function stepBoat(boat, dt, windDir, gust, input, opts = {}) {
  const authority = Math.max(0, Math.min(1, boat.speed / 3));
  boat.heading = normalizeAngle(boat.heading + Math.max(-1, Math.min(1, input.turn)) * TURN_RATE * authority * dt);
  const params2 = getBoatParams();
  const state = {
    ...boat.physics ?? createInitialState({ tws: 12 }),
    heading: boat.heading,
    boatSpeed: boat.speed,
    trueWindDir: windDir,
    trueWindSpeed: 12 * (opts.windStrengthMul ?? 1) * gust
  };
  boat.trimClock = (boat.trimClock ?? 1) + dt;
  if (!boat.trim || boat.trimClock >= 0.5) {
    boat.trim = trimForDrive(state, boat.trim ?? { mainSheet: 0.4, jibSheet: 0.2, mainTwist: 0.35, jibTwist: 0.4, reef: 0, jibFurl: 0, jibSide: 1 });
    boat.trimClock = 0;
  }
  boat.physics = tick(state, boat.trim, params2, dt).state;
  boat.speed = boat.physics.boatSpeed;
  const rad = deg2rad(boat.heading + boat.physics.leeway);
  boat.pos.x += Math.sin(rad) * boat.speed * 8 * dt;
  boat.pos.y -= Math.cos(rad) * boat.speed * 8 * dt;
  boat.pos.x = Math.max(20, Math.min(WORLD.width - 20, boat.pos.x));
  boat.pos.y = Math.max(20, Math.min(WORLD.height - 20, boat.pos.y));
}
function resolveCollisions(boats, dt = 1 / 20) {
  for (let i = 0; i < boats.length; i++) {
    for (let j = i + 1; j < boats.length; j++) {
      const a = boats[i];
      const b = boats[j];
      const dx = b.pos.x - a.pos.x;
      const dy = b.pos.y - a.pos.y;
      const d = Math.hypot(dx, dy);
      if (d < MIN_BOAT_SEPARATION) {
        const overlap = (MIN_BOAT_SEPARATION - d) / 2;
        const nx = d > 1e-3 ? dx / d : 1;
        const ny = d > 1e-3 ? dy / d : 0;
        a.pos.x -= nx * overlap;
        a.pos.y -= ny * overlap;
        b.pos.x += nx * overlap;
        b.pos.y += ny * overlap;
        a.speed *= Math.exp(-1.67 * dt);
        b.speed *= Math.exp(-1.67 * dt);
      }
    }
  }
}
function makeStandardCourse() {
  const cx = WORLD.width / 2;
  const startY = WORLD.height - 150;
  const windwardY = 180;
  const startLine = {
    a: { x: cx - 80, y: startY },
    b: { x: cx + 80, y: startY }
  };
  return {
    marks: [
      { pos: { x: cx, y: windwardY }, radius: 14, label: "Windward", type: "windward" },
      { pos: startLine.a, radius: 10, label: "Start L", type: "start" },
      { pos: startLine.b, radius: 10, label: "Start R", type: "start" }
    ],
    startLine,
    finishLine: startLine
  };
}
function updateLap(boat, prevPos, course, raceTime) {
  if (!boat.started) {
    if (prevPos.y > boat.pos.y && segmentCrossed(prevPos, boat.pos, course.startLine.a, course.startLine.b)) boat.started = true;
    else return null;
  }
  if (boat.lapDone === 0) {
    const m = course.marks[0];
    const inner = m.radius + MIN_BOAT_SEPARATION / 2;
    const outer = inner + 70;
    const x = m.pos.x, y = m.pos.y;
    const phase = boat.roundPhase ?? 0;
    if (phase === 0 && boat.pos.y < prevPos.y && segmentCrossed(prevPos, boat.pos, { x: x + inner, y }, { x: x + outer, y })) boat.roundPhase = 1;
    else if (phase === 1 && boat.pos.x < prevPos.x && segmentCrossed(prevPos, boat.pos, { x, y: y - inner }, { x, y: y - outer })) boat.roundPhase = 2;
    else if (phase === 2 && boat.pos.y > prevPos.y && segmentCrossed(prevPos, boat.pos, { x: x - inner, y }, { x: x - outer, y })) {
      boat.lapDone = 1;
      return "mark";
    }
  } else if (boat.lapDone === 1 && prevPos.y < boat.pos.y && segmentCrossed(prevPos, boat.pos, course.finishLine.a, course.finishLine.b)) {
    boat.lapDone = 2;
    boat.finishTime = raceTime;
    return "finish";
  }
  return null;
}
function raceWaypoint(boat, course) {
  if (!boat.started) {
    const y = course.startLine.a.y;
    if (boat.pos.y < y) boat.returningToStart = true;
    if (boat.pos.y > y + 35) boat.returningToStart = false;
    return { x: (course.startLine.a.x + course.startLine.b.x) / 2, y: y + (boat.returningToStart ? 60 : -60) };
  }
  if (boat.lapDone > 0) return { x: (course.finishLine.a.x + course.finishLine.b.x) / 2, y: course.finishLine.a.y + 30 };
  const m = course.marks[0].pos;
  const r = course.marks[0].radius + MIN_BOAT_SEPARATION / 2 + 35;
  if ((boat.roundPhase ?? 0) === 0) return { x: m.x + r, y: m.y - r };
  if (boat.roundPhase === 1) return { x: m.x - r, y: m.y - r };
  return { x: m.x - r, y: m.y + r };
}
function raceAutopilotTurn(boat, course, windDir) {
  const target = raceWaypoint(boat, course);
  let desired = bearing(boat.pos, target);
  const relative = calcTWA(desired, windDir);
  if (Math.abs(relative) < 45) {
    const crosswind = (target.x - boat.pos.x) * Math.cos(deg2rad(windDir)) + (target.y - boat.pos.y) * Math.sin(deg2rad(windDir));
    desired = normalizeAngle(windDir + (crosswind >= 0 ? 48 : -48));
  }
  return Math.max(-1, Math.min(1, angleDiff(boat.heading, desired) / 12));
}
export {
  ACCEL,
  MARK_ROUND_DIST,
  MAX_SPEED,
  MIN_BOAT_SEPARATION,
  TURN_RATE,
  WIND_DIRECTION_BASE,
  WORLD,
  angleDiff,
  bearing,
  calcTWA,
  deg2rad,
  distance,
  makeStandardCourse,
  normalizeAngle,
  raceAutopilotTurn,
  raceWaypoint,
  rad2deg,
  resolveCollisions,
  segmentCrossed,
  speedFactorFromTWA,
  stepBoat,
  updateLap,
  windAt
};
